version: "2"

run:
  timeout: 5m
  verbose: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  default: standard
  enable:
    - copyloopvar
    - dupl
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - predeclared
    - usestdlibvars
    - unparam
    - unconvert
  settings:
    gocyclo:
      min-complexity: 20
    iface:
      enable:
        - identical
        - unused
    dupl:
      threshold: 200
    errcheck:
      check-type-assertions: true
      check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: strict

