services:
  postgres-db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - migrations
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend

  liquibase-migrate:
    build:
      context: ./migrations
      dockerfile: Dockerfile.liquibase
    container_name: db-migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MIGRATION_VERSION: ${MIGRATION_VERSION}
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_DRIVER: postgresql
    command: 
      - "/liquibase/changelog/scripts/migrate.sh"
    networks:
      - migrations

  accounts:
      build:
        context: ./
        dockerfile: ./cmd/Dockerfile
      container_name: accounts
      env_file:
        - ./.env
      depends_on:
        postgres-db:
          condition: service_healthy
      networks:
        - backend
      ports:
        - "9112:8080"

networks:
  migrations:
    driver: bridge
  backend:
    driver: bridge
    name: shared-backend