services:
  postgres-db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - .pgdata:/var/lib/postgresql/data
    networks:
      - migrations
      - backend

  liquibase-migrate:
    build:
      context: ./migrations
      dockerfile: Dockerfile.liquibase
    container_name: db-migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MIGRATION_VERSION: ${MIGRATION_VERSION}
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_DRIVER: postgresql
    command: 
      - "/liquibase/changelog/scripts/migrate.sh"
    networks:
      - migrations

volumes:
  .pgdata:

networks:
  migrations:
    driver: bridge
  backend:
    external: true
    name: shared-backend