filebeat.inputs:
  - type: filestream
    id: app-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    json.keys_under_root: false
    json.add_error_key: true
    scan_frequency: 1s

    processors:
      - script:
          lang: javascript
          id: parse_json
          source: >
            function process(event) {
              try {
                var msg = JSON.parse(event.Get("message"));
            
                if (msg["log.level"]) {
                  event.Put("level", msg["log.level"]);
                  delete msg["log.level"];
                }

                if (msg.correlation_id) {
                  event.Put("correlation_id", msg.correlation_id);
                  delete msg.correlation_id;
                }

                event.Put("message", JSON.stringify(msg));
              } catch(e) {}
            }

setup.template.name: "app-logs"
setup.template.pattern: "app-logs-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"